In [1]:
import numpy as np
import pandas as pd
import datetime

In [2]:
link_df = pd.read_csv('../../data/original/links (table 3).csv', index_col=0)

In [48]:
#validation_path = '../../data/offline/validation_9_5/'
#validation_path = '../../data/offline/validation_9_20/'
validation_path = '../../data/offline/validation_10_11/'

#window_date = pd.to_datetime('2016-09-06')
#window_date = pd.to_datetime('2016-09-20')
window_date = pd.to_datetime('2016-10-11')

In [49]:
afternoon_predict_dict = {}
morning_predict_dict = {}

afternoon_real_dict = {}
morning_real_dict = {}

for link_id in link_df.index.values:
    predict_afternoon_m1_df = pd.read_csv(validation_path + 'prediction/afternoon/m1_' + str(link_id) + '.csv', index_col=0)
    
    predict_morning_m1_df = pd.read_csv(validation_path + 'prediction/morning/m1_' + str(link_id) + '.csv', index_col=0)
    
    real_afternoon_m1_df = pd.read_csv(validation_path + 'feature/feature1/afternoon/y_test_link' + str(link_id) + '.csv', index_col = 0)
    
    real_morning_m1_df = pd.read_csv(validation_path + 'feature/feature1/morning/y_test_link' + str(link_id) + '.csv', index_col = 0)
    
    afternoon_predict_dict[link_id] = predict_afternoon_m1_df
    morning_predict_dict[link_id] = predict_morning_m1_df
    
    afternoon_real_dict[link_id] = real_afternoon_m1_df
    morning_real_dict[link_id] = real_morning_m1_df

In [50]:
def ArrayMape(ground_truth, predictions):
    diff = (ground_truth - predictions) / ground_truth
    diff = np.abs(diff)
    mape = diff.sum() / ground_truth.size
    
    return mape

In [51]:
def ScalarMape(ground_truth, predictions):
    diff = (ground_truth - predictions) / ground_truth
    diff = np.abs(diff)
    mape = diff
    
    return mape

In [56]:
routes = pd.read_csv('../../data/original/routes (table 4).csv')
submissions = []
for i in routes.index:
    
    link_seq = routes.loc[i]['link_seq']
    links = link_seq.split(',')
    
    #morning
    y_test_time = pd.read_csv(validation_path + 'feature/feature3/morning/y_test_route' + str(i) + '.csv', index_col = 0)
    y_predict_time = pd.read_csv(validation_path + 'prediction/feature3/morning/predict_' + str(i) + '.csv', index_col = 0)
    start_time = window_date + datetime.timedelta(hours=8)
    for d in range(7):
        current_time = start_time
        for t in range(6):
            predict_time = 0
            real_time = 0
            record = []
            record.append(routes.loc[i]['intersection_id'])
            record.append(routes.loc[i]['tollgate_id'])
            record.append('[' + str(current_time) + ',' + str(current_time + datetime.timedelta(minutes=20)) + ')')
            for link_id in links:
                predict_time = predict_time + morning_predict_dict[int(link_id)].loc[d][t]
                real_time = real_time + morning_real_dict[int(link_id)].loc[d][t]
                
            predict_time = predict_time + y_predict_time.loc[d][t]
            real_time = real_time + y_test_time.loc[d][t]
            
            record.append(predict_time)
            record.append(real_time)

            submissions.append(record)
            current_time = current_time + datetime.timedelta(minutes=20)
            
        start_time = start_time + datetime.timedelta(days=1)
        
    #afternoon
    y_test_time = pd.read_csv(validation_path + 'feature/feature3/afternoon/y_test_route' + str(i) + '.csv', index_col = 0)
    y_predict_time = pd.read_csv(validation_path + 'prediction/feature3/afternoon/predict_' + str(i) + '.csv', index_col = 0)
    start_time = window_date + datetime.timedelta(hours=17)
#     start_time = pd.to_datetime('2016-09-20 17:00:00')
#     start_time = pd.to_datetime('2016-10-11 17:00:00')
    for d in range(7):
        current_time = start_time
        for t in range(6):
            predict_time = 0
            real_time = 0
            record = []
            record.append(routes.loc[i]['intersection_id'])
            record.append(routes.loc[i]['tollgate_id'])
            record.append('[' + str(current_time) + ',' + str(current_time + datetime.timedelta(minutes=20)) + ')')
            for link_id in links:
                predict_time = predict_time + afternoon_predict_dict[int(link_id)].loc[d][t] 
                real_time = real_time + afternoon_real_dict[int(link_id)].loc[d][t] 
            
            predict_time = predict_time + y_predict_time.loc[d][t]
            real_time = real_time + y_test_time.loc[d][t] 
            
            record.append(predict_time)
            record.append(real_time)

            submissions.append(record)
            current_time = current_time + datetime.timedelta(minutes=20)
            
        start_time = start_time + datetime.timedelta(days=1)

In [57]:
submission_df = pd.DataFrame(submissions).rename(columns={0:'intersection_id', 1:'tollgate_id', 2:'time_window', 3:'predict_time', 4:'real_time'})

In [58]:
submission_df['mape'] = ArrayMape(submission_df['real_time'].values, submission_df['predict_time'].values)

In [59]:
mape_sum = 0
mapes = []
for i in range(len(submission_df)):
    mape = ScalarMape(submission_df.loc[i]['real_time'], submission_df.loc[i]['predict_time'])
    #print('%a-%d : %f'%(m[0], m[1], mape))
    mapes.append(mape)
    mape_sum = mape_sum + mape
    
submission_df['mape'] = mapes
print("mape=%f"%(mape_sum / len(submissions)))

mape=0.179141

In [ ]:
1, mape=0.195559, 0.223741
2, mape=0.151659 0.177074
3, mape=0.152054 0.179141

In [11]:
submission_df[submission_df['mape'] > 0.31]

,intersection_id,tollgate_id,time_window,predict_time,real_time,mape
24,A,2,"[2016-10-15 08:00:00,2016-10-15 08:20:00)",73.227330,108.723522,0.326481
26,A,2,"[2016-10-15 08:40:00,2016-10-15 09:00:00)",82.697393,142.464061,0.419521
27,A,2,"[2016-10-15 09:00:00,2016-10-15 09:20:00)",74.519494,139.360072,0.465274
28,A,2,"[2016-10-15 09:20:00,2016-10-15 09:40:00)",73.829183,149.606823,0.506512
29,A,2,"[2016-10-15 09:40:00,2016-10-15 10:00:00)",72.318057,159.099324,0.545453
36,A,2,"[2016-10-17 08:00:00,2016-10-17 08:20:00)",72.415644,130.193056,0.443783
41,A,2,"[2016-10-17 09:40:00,2016-10-17 10:00:00)",72.173583,53.130935,0.358410
46,A,2,"[2016-10-11 09:20:00,2016-10-11 09:40:00)",66.663553,155.819733,0.572175
82,A,2,"[2016-10-17 09:20:00,2016-10-17 09:40:00)",65.793224,47.478974,0.385734
92,A,3,"[2016-10-12 08:40:00,2016-10-12 09:00:00)",150.367142,223.765667,0.328015
106,A,3,"[2016-10-14 09:20:00,2016-10-14 09:40:00)",162.192878,121.181587,0.338428
108,A,3,"[2016-10-15 08:00:00,2016-10-15 08:20:00)",128.998056,372.914269,0.654081
109,A,3,"[2016-10-15 08:20:00,2016-10-15 08:40:00)",148.889627,335.814063,0.556631
110,A,3,"[2016-10-15 08:40:00,2016-10-15 09:00:00)",147.117652,406.867727,0.638414
111,A,3,"[2016-10-15 09:00:00,2016-10-15 09:20:00)",160.059384,357.402106,0.552159
112,A,3,"[2016-10-15 09:20:00,2016-10-15 09:40:00)",161.489851,347.777898,0.535652
113,A,3,"[2016-10-15 09:40:00,2016-10-15 10:00:00)",138.295110,510.886115,0.729303
120,A,3,"[2016-10-17 08:00:00,2016-10-17 08:20:00)",128.343076,321.939167,0.601344
121,A,3,"[2016-10-17 08:20:00,2016-10-17 08:40:00)",145.891818,320.541701,0.544859
122,A,3,"[2016-10-17 08:40:00,2016-10-17 09:00:00)",147.723139,296.119372,0.501137
123,A,3,"[2016-10-17 09:00:00,2016-10-17 09:20:00)",159.122668,340.565103,0.532769
148,A,3,"[2016-10-14 09:20:00,2016-10-14 09:40:00)",145.916882,109.098852,0.337474
149,A,3,"[2016-10-14 09:40:00,2016-10-14 10:00:00)",121.449649,187.004778,0.350553
154,A,3,"[2016-10-15 09:20:00,2016-10-15 09:40:00)",167.294179,102.888429,0.625977
155,A,3,"[2016-10-15 09:40:00,2016-10-15 10:00:00)",125.346976,190.557952,0.342211
167,A,3,"[2016-10-17 09:40:00,2016-10-17 10:00:00)",123.050205,224.647917,0.452253
170,B,1,"[2016-10-11 08:40:00,2016-10-11 09:00:00)",134.148445,94.922500,0.413242
189,B,1,"[2016-10-14 09:00:00,2016-10-14 09:20:00)",142.609377,104.055000,0.370519
195,B,1,"[2016-10-15 09:00:00,2016-10-15 09:20:00)",142.769369,108.119542,0.320477
203,B,1,"[2016-10-16 09:40:00,2016-10-16 10:00:00)",133.003009,98.562536,0.349428
...,...,...,...,...,...,...
328,B,3,"[2016-10-16 09:20:00,2016-10-16 09:40:00)",141.794126,71.872500,0.972856
330,B,3,"[2016-10-17 08:00:00,2016-10-17 08:20:00)",103.938302,74.241095,0.400010
334,B,3,"[2016-10-17 09:20:00,2016-10-17 09:40:00)",123.470706,92.271875,0.338119
335,B,3,"[2016-10-17 09:40:00,2016-10-17 10:00:00)",100.079286,196.606111,0.490966
351,C,1,"[2016-10-13 09:00:00,2016-10-13 09:20:00)",206.391638,153.690000,0.342909
352,C,1,"[2016-10-13 09:20:00,2016-10-13 09:40:00)",213.406326,154.021667,0.385560
375,C,1,"[2016-10-17 09:00:00,2016-10-17 09:20:00)",204.148089,141.863750,0.439043
378,C,1,"[2016-10-11 08:00:00,2016-10-11 08:20:00)",215.445382,150.098250,0.435362
380,C,1,"[2016-10-11 08:40:00,2016-10-11 09:00:00)",211.568501,308.765000,0.314791
384,C,1,"[2016-10-12 08:00:00,2016-10-12 08:20:00)",215.340402,151.305606,0.423215
398,C,1,"[2016-10-14 08:40:00,2016-10-14 09:00:00)",214.800005,398.157750,0.460515
402,C,1,"[2016-10-15 08:00:00,2016-10-15 08:20:00)",222.187001,345.926657,0.357705
406,C,1,"[2016-10-15 09:20:00,2016-10-15 09:40:00)",264.923915,177.340000,0.493876
414,C,1,"[2016-10-17 08:00:00,2016-10-17 08:20:00)",217.722121,155.355333,0.401446
435,C,3,"[2016-10-13 09:00:00,2016-10-13 09:20:00)",169.666398,127.271026,0.333111
436,C,3,"[2016-10-13 09:20:00,2016-10-13 09:40:00)",177.813835,125.103667,0.421332
442,C,3,"[2016-10-14 09:20:00,2016-10-14 09:40:00)",175.112916,131.628353,0.330359
454,C,3,"[2016-10-16 09:20:00,2016-10-16 09:40:00)",175.343831,128.033910,0.369511
462,C,3,"[2016-10-11 08:00:00,2016-10-11 08:20:00)",173.430416,126.877417,0.366913
468,C,3,"[2016-10-12 08:00:00,2016-10-12 08:20:00)",174.067303,120.538273,0.444083
472,C,3,"[2016-10-12 09:20:00,2016-10-12 09:40:00)",221.395285,163.735333,0.352153
482,C,3,"[2016-10-14 08:40:00,2016-10-14 09:00:00)",179.170215,296.684000,0.396091
484,C,3,"[2016-10-14 09:20:00,2016-10-14 09:40:00)",222.201262,156.997619,0.415316
486,C,3,"[2016-10-15 08:00:00,2016-10-15 08:20:00)",174.319264,278.871760,0.374912
487,C,3,"[2016-10-15 08:20:00,2016-10-15 08:40:00)",167.611719,248.087865,0.324386
490,C,3,"[2016-10-15 09:20:00,2016-10-15 09:40:00)",277.201085,151.104000,0.834505
496,C,3,"[2016-10-16 09:20:00,2016-10-16 09:40:00)",276.053617,160.895833,0.715729
498,C,3,"[2016-10-17 08:00:00,2016-10-17 08:20:00)",173.640869,124.072762,0.399508
500,C,3,"[2016-10-17 08:40:00,2016-10-17 09:00:00)",177.056853,132.744485,0.333817
503,C,3,"[2016-10-17 09:40:00,2016-10-17 10:00:00)",186.827387,292.091111,0.360380